<?php
header('content-type:text/html;charset=utf-8;');
error_reporting(0);
session_start();
if($_SESSION['username']==null){
    header("location:test.php");
}else{
    header("location:loginOK.php");
}